// <auto-generated />
namespace Chem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig4));
        
        string IMigrationMetadata.Id
        {
            get { return "201501061333092_mig4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
